#!/bin/bash

PROJECT=$1
KEYFILE=$2

if [ -z "$PROJECT" ] || [ -z "$KEYFILE" ]; then
  echo "ERRO: Os parâmetros PROJECT e KEYFILE são obrigatórios."
  exit 1
fi

echo "$KEYFILE" | base64 -d > ./gcloud-api-key.json
gcloud auth activate-service-account --key-file ./gcloud-api-key.json
gcloud config set project "$PROJECT"
docker login -u _json_key -p "$(cat ./gcloud-api-key.json)" https://gcr.io

exit 0
