#!/bin/bash

prefix=$(date +%y%m)

tag=$(
  git for-each-ref \
    --sort='-version:refname' \
    --count=1 \
    --format='%(refname:short)' \
    "refs/tags/${prefix}.*"
)

if [[ -z "${tag}" ]]; then
  echo "${prefix}.0"
else
  echo "$tag" | cut -d. -f2 | xargs expr 1 +
fi

exit 0
