#!/bin/bash

function exit_on_error() {
  local exit_code=$?
  if [ "$exit_code" -ne 0 ]; then
    exit "$exit_code"
  fi
}

declare -a tags images
while getopts ":k:i:p:t:" OPT; do
  case "$OPT" in
  k)
    keyfile="$OPTARG"
    ;;
  i)
    images+=("$OPTARG")
    ;;
  p)
    project="$OPTARG"
    ;;
  t)
    tags+=("$OPTARG")
    ;;
  \?)
    echo "Opção ${OPT} inválida."
    ;;
  esac
done

echo "Projeto: $project"
echo "Imagem: $image"
[[ -n $keyfile ]] && echo "Keyfile: Existe" || echo "Keyfile: Não existe"

if [ -z "$project" ] || [ -z "$keyfile" ] || [ -z "$image" ]; then
  echo "ERRO: As opções -k -p e -i são obrigatórias."
  exit 1
fi

if [ "${#tags[@]}" -eq 0 ]; then
  echo "ERRO: Especifique pelo menos uma tag com -t 'tag'"
  exit 1
fi

if [ "${#images[@]}" -eq 0 ]; then
  echo "ERRO: Especifique pelo menos uma imagem com -i 'image'"
  exit 1
fi

docker-login "$project" "$keyfile"
exit_on_error

if [ -f ./image.docker ]; then
  docker load --input ./image.docker 1> /dev/null
fi

for image in "${images[@]}"; do
  if (! docker image inspect "$image" &> /dev/null); then
    if [ -f "$image.docker" ]; then
      docker load --input "$image.docker" 1> /dev/null
    else
      echo "ERROR: neither image={${image}} nor ${image}.docker file exists"
      exit 1
    fi
  fi
done

declare -a published
for image in "${images[@]}"; do
  repository="gcr.io/$project/$image"

  for tag in "${tags[@]}"; do
    to_publish="$repository:$tag"

    docker tag "$image" "$to_publish"
    docker push "$to_publish"

    published+=("$to_publish")
  done
done

echo "Imagens publicadas"
for image in "${published[@]}"; do
  echo "$image"
done

